dashboard/urls.py
from django.conf.urls import url 
from . import views 

app_name = 'dashboard'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^create/$', views.post_question, name="create_ques"),
    url(r'^$', views.question_list, name="question_list"),
    url(r'^(?P<id>[\w]+)/$', views.question_detail, name="detail"),
    url(r'^(?P<id>[\w]+)/answer$', views.post_answer, name="post_answer"),
    url('get_questions', views.get_questions),
    url('post_question', views.post_question_api),
]

stackclone/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls'), name="dashboard"),
    url(r'^$', views.homepage, name="home")
]

dashboard/models.py
# python manage.py makemigrations
# python manage.py migrate

from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.
class Questions(models.Model):
    ques_text = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    # upvotes = models.SmallIntegerField()
    ques_title = models.TextField()
    posted_by = models.ForeignKey(User, default=None, on_delete=CASCADE)

class Answers(models.Model):
    ans_text = models.TextField()
    answered_by =  models.ForeignKey(User, default=None, on_delete=CASCADE)
    answered_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Questions, default=None, on_delete=CASCADE)
    # upvotes = models.SmallIntegerField()

dashboard/forms.py
from django import forms
from . import models

class CreateQuestion(forms.ModelForm):
    class Meta:
        model = models.Questions
        fields = ['ques_title', 'ques_text']
        # fields = ['title', 'body', 'slug', 'thumb',]

class CreateAnswer(forms.ModelForm):
    class Meta:
        model = models.Answers
        fields = ['ans_text']

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Answers, Questions
from . import forms
from rest_framework.decorators import parser_classes
from rest_framework.parsers import JSONParser

from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .serializers import QuestionsSerializer, AnswersSerializer
from .models import Answers, Questions
from rest_framework import status

from dashboard import serializers

def question_list(request):
    questions = Questions.objects.all().order_by('posted_at');
    return render(request, 'question_list.html', { 'questions': questions })

def question_detail(request, id):
    question = Questions.objects.get(id=id)
    answers = Answers.objects.filter(question_id=id)
    print(answers)
    return render(request, 'question_detail.html', { 'question': question, 'answers':answers })

@login_required(login_url="/dashboard/login/")
def post_answer(request, id):
    question = Questions.objects.get(id=id)
    if request.method == 'POST':
        form = forms.CreateAnswer(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.answered_by = request.user
            instance.question = question
            instance.save()
            return redirect('dashboard:detail', id=id) 
            # render(request, 'question_detail.html', { 'question': question})
    else:
        form = forms.CreateAnswer()
    return render(request, 'question_detail.html', { 'question': question, 'form': form})

@login_required(login_url="/dashboard/login/")
def post_question(request):
    if request.method == 'POST':
        form = forms.CreateQuestion(request.POST, request.FILES)
        if form.is_valid():
            # save question to db
            instance = form.save(commit=False)
            instance.posted_by = request.user
            instance.save()
            return redirect('dashboard:question_list')
    else:
        form = forms.CreateQuestion()
    return render(request, 'post_question.html', { 'form': form })


def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('dashboard:question_list')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('dashboard:question_list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('dashboard:question_list')

# get all questions
@api_view(["GET"])
def get_questions(request):
    questions = Questions.objects.all()
    serializer = QuestionsSerializer(questions, many=True)
    return JsonResponse({'questions':serializer.data}, safe=False, status=status.HTTP_200_OK)

# get ques by id

# update ques

# post ques
@api_view(["POST"])
@csrf_exempt
@parser_classes((JSONParser,))
@permission_classes([IsAuthenticated])
def post_question_api(request):
    print(request.data)
    payload = request.data
    user = request.user
    try:
        ques = Questions.objects.create(
            ques_title = payload["ques_title"],
            ques_text = payload["ques_text"],
            posted_by = user
        )
        serializer = QuestionsSerializer(ques)
        return JsonResponse({'question': serializer.data}, safe=False, status=status.HTTP_201_CREATED)
    except Exception:
        return JsonResponse({'error': 'Something went wrong'}, safe=False, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

# delete ques

# show ans to ques by ques id

stackclone/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

# def about(request):
#     # return HttpResponse('about')
#     return render(request, 'about.html')

dashboard/templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'dashboard:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'dashboard:signup' %}">Sign Up</a></p>
{% endblock %}

dashboard/templates/post_answer.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="post-answer">
        <h2>Post Your Answer Here</h2>
        <form class="site-form" action="{% url 'dashboard:post_answer' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post Answer">
        </form>
    </div>
{% endblock %}

dashboard/templates/post_question.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="post-question">
        <h2>Post Your Question Here</h2>
        <form class="site-form" action="{% url 'dashboard:create_ques' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post Question">
        </form>
    </div>
    <!-- <script src="/static/slugify.js"></script> -->
{% endblock %}

dashboard/templates/question_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="question-detail">
    <div class="question">
        <h2>{{ question.ques_title }}</h2>
        <h3>Written by {{ question.posted_by.username }}</h3>
        <h6>Posted at {{ question.posted_at }}</h6>
        <p>{{ question.ques_text }}</p>
    </div>
    <div class="post-answer">
        <h3>Post Your Answer here</h3>
        <form class="site-form" action="{% url 'dashboard:post_answer' id=question.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post Answer">
        </form>
    </div>
    <div class="answers">
        {% for answer in answers %}
            <div class="answer">
                 <p>{{ answer.ans_text }}</p>
                 <p>Answered by {{ answer.answered_by.username }} at {{ answer.answered_at }}</p>
                 <p></p>
                <!-- posted by -->
                <!-- posted at -->
            </div>
        {% endfor %}
    </div>        
</div>
{% endblock %}

dashboard/templates/question_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Questions List</h1>
    <div class="questions">
    {% for question in questions %}
        <div class="question">
            <h2><a href="{% url 'dashboard:detail' id=question.id %}">{{ question.ques_title }}</a></h2>
            <p>{{ question.ques_text }}</p>
            <p>{{ question.posted_at }}</p>
            <p>Posted By {{ question.posted_by.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

dashboard/templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'dashboard:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

templates/about.html
<!DOCTYPE html>
    <body>
        <h1>About</h1>
    </body>
</html>

templates/base_layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>StackClone</title>
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}">Stackclone</a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'dashboard:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'dashboard:create_ques' %}" class="highlight">Post Question</a></li>
                    {% else %}
                    <li><a href="{% url 'dashboard:login' %}">Login</a></li>
                    <li><a href="{% url 'dashboard:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
    <body>
        <h1>Homepage</h1>
        <h2>Go to <a href="{% url 'dashboard:question_list' %}">Stackclone</a></h2>
    </body>
</html>